esphome:
  name: garage-door
  friendly_name: Garage Door
  min_version: 2025.7.0

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api-key

ota:
  - platform: esphome
    password: !secret ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: !secret fallbak-hotspot-pw

captive_portal:

# Custom config follows now

# Import component directly from Github, always refreshing, using latest commit on master branch
external_components:
  - source:
      type: git
      url: https://github.com/jpmeijers/dc-blue-esphome
      ref: master
    refresh: 0s
    components: [ dc_blue ]

# Initialise the platform
dc_blue:
  # Required: Pin where data is received
  data_pin: GPIO33
  # Required: Pin which is pulled high to "press button"
  trigger_pin: GPIO32
  # Optional: Time per symbol in us
  symbol_period: 970
  # Optional: Is the signal from the motor inverted by optocoupler?
  inverted: True
  # Optional: Time to press button in ms
  trigger_period: 1000
  # Optional: Minimum time between presses in ms
  clear_period: 1000


binary_sensor:
  # Add if you want a binary sensor following the garage door motor light
  - platform: dc_blue
    light:
      name: "Garage Motor Light"

  # Add if you want a binary sensor following the garage door motor AC mains supply status
  - platform: dc_blue
    ac_power:
      name: "Garage Motor AC supply"      

# Add a cover sensor for the door state and control
cover:
  - platform: dc_blue
    name: "Garage Door (BMW)"
    device_class: garage
