esphome:
  name: garage-door
  friendly_name: Garage Door

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api-key

ota:
  - platform: esphome
    password: !secret ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: !secret fallbak-hotspot-pw

captive_portal:

# Custom config follows now

# Import component directly from Github, always refreshing, using latest commit on master branch
external_components:
  - source:
      type: git
      url: https://github.com/jpmeijers/dc-blue-esphome
      ref: master
    refresh: 0s
    components: [ dc_blue ]

# Initialise the platform
dc_blue:
  data_pin: GPIO33
  trigger_pin: GPIO32
  symbol_period: 970


binary_sensor:
  # Add if you want a binary sensor following the garage door motor light
  - platform: dc_blue
    light:
      name: "Garage Motor Light"

  # Add if you want a binary sensor following the garage door motor AC mains supply status
  - platform: dc_blue
    ac_power:
      name: "Garage Motor AC supply"      

# Add a cover sensor for the door state and control
cover:
  - platform: dc_blue
    name: "Garage Door (BMW)"
    device_class: garage
